Fix web emscripten bindings, bump to 0.1.26 (#456)
Running `cd web; npm run build` against the latest main yields these
errors:

```log
+ emcc --bind -o src/xgrammar_binding.js src/xgrammar_binding.cc build/libxgrammar.a -O3 -s EXPORT_ES6=1 -s ERROR_ON_UNDEFINED_SYMBOLS=0 -s NO_DYNAMIC_EXECUTION=1 -s MODULARIZE=1 -s SINGLE_FILE=1 -s EXPORTED_RUNTIME_METHODS=FS -s ALLOW_MEMORY_GROWTH=1 -I../include -I../3rdparty/picojson -I../3rdparty/dlpack/include
src/xgrammar_binding.cc:147:34: error: use of undeclared identifier '_JSONSchemaToEBNF'
  147 |   function("_JSONSchemaToEBNF", &_JSONSchemaToEBNF);
      |                                  ^~~~~~~~~~~~~~~~~
src/xgrammar_binding.cc:169:8: error: no matching member function for call to 'function'
  165 |   class_<GrammarCompiler>("GrammarCompiler")
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  166 |       .constructor<const TokenizerInfo&, int, bool>()
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  167 |       .function("CompileJSONSchema", &GrammarCompiler::CompileJSONSchema)
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  168 |       .function("CompileBuiltinJSONGrammar", &GrammarCompiler::CompileBuiltinJSONGrammar)
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  169 |       .function("CompileGrammar", &GrammarCompiler::CompileGrammar)
      |       ~^~~~~~~~
/home/logan/emsdk/upstream/emscripten/cache/sysroot/include/emscripten/bind.h:1577:44: note: candidate template ignored: couldn't infer template argument 'Callable'
 1577 |     EMSCRIPTEN_ALWAYS_INLINE const class_& function(const char* methodName, Callable callable, Policies...) const {
      |                                            ^
src/xgrammar_binding.cc:182:56: error: no member named '_DebugAcceptString' in 'xgrammar::GrammarMatcher'
  182 |       .function("_DebugAcceptString", &GrammarMatcher::_DebugAcceptString);
      |                                                        ^~~~~~~~~~~~~~~~~~
3 errors generated.
```

It seems these were changed in #123 (_JSONSchemaToEBNF relocated), #327
(_DebugAcceptString renamed), #428 (CompileGrammar gains overload)

I've:

1. Asked Claude to update these bindings for me
2. Tested the web example app
3. Built `web-llm` using this version of `web-xgrammar` and tested chat
completions in my own app (grammar-constrained generation is much faster
thanks to #308!)

<img width="964" height="477" alt="image"
src="https://github.com/user-attachments/assets/8529375c-ab3c-454b-91fd-e18134584035"
/>

---------

Co-authored-by: Yixin Dong <ubospica@gmail.com>